---
kind: pipeline
name: linting

platform:
  os: linux
  arch: amd64

steps:
- name: later
  image: xoxys/ansible-later:latest
  pull: always
  commands:
    - ansible-later

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: readme

platform:
  os: linux
  arch: amd64

steps:
- name: doctor
  image: xoxys/ansible-doctor:latest
  pull: always
  environment:
    ANSIBLE_DOCTOR_LOG_LEVEL: INFO
    ANSIBLE_DOCTOR_FORCE_OVERWRITE: true
    ANSIBLE_DOCTOR_EXCLUDE_FILES: molecule/
    ANSIBLE_DOCTOR_CUSTOM_HEADER: misc/HEADER.md

- name: commit
  pull: always
  image: plugins/git-action:latest
  settings:
    actions:
    - commit
    - push
    author_email: drone@webhippie.de
    author_name: Drone
    branch: master
    message: [skip ci] update readme
    remote: https://github.com/${DRONE_REPO}
    netrc_machine: github.com
    netrc_username:
      from_secret: github_username
    netrc_password:
      from_secret: github_token
  when:
    ref:
    - refs/heads/master

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
  - linting

---
kind: pipeline
name: notification

platform:
  os: linux
  arch: amd64

steps:
- name: matrix
  image: plugins/matrix:latest
  settings:
    homeserver: https://matrix.org
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    username:
      from_secret: matrix_username

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
  - linting
  - readme

...
